export const LABELS = {
    APP_TITLE: "CROP ANALYSIS: IMAGE UPLOAD",
    APP_SUBTITLE: "LOFI WIREFRAME - DATA ENTRY MODULE",
    SECTION_IMAGERY_UPLOAD: "1. IMAGERY UPLOAD",
    SECTION_INPUT_DATA: "2. INPUT DATA",
    SECTION_IMAGERY_PREVIEW: "IMAGERY PREVIEW",

    UPLOAD_BOX_TITLE: "DROP DRONE/SATELLITE IMAGERY",
    UPLOAD_BOX_SUBTITLE: "TIFF, JPG, PNG UP TO 500MB PER FILE. MULTI-SPECTRAL SUPPORTED.",
    BROWSE_BUTTON: "BROWSE STORAGE",

    FIELD_TARGET_YIELD: "TARGET YIELD (T/HA)",
    FIELD_LOCATION: "LOCATION ID / NAME",
    FIELD_SOIL: "SOIL CATEGORY",
    FIELD_MOISTURE: "CURRENT MOISTURE LEVEL",
    FIELD_MOISTURE_DRY: "DRY",
    FIELD_MOISTURE_OPTIMAL: "OPTIMAL",
    FIELD_MOISTURE_WET: "WET",
    FIELD_ANOMALY: "ENABLE AI ANOMALY DETECTION PROTOCOL",

    CANCEL_BUTTON: "CANCEL",
    START_BUTTON: "START ANALYSIS",

    ERROR_FILE_SIZE: "File size exceeds 500MB limit.",
    ERROR_FILE_TYPE: "Unsupported file type. Please use JPG, PNG, or TIFF.",
    EMPTY_PREVIEW: "NO CONTENT SELECTED",
    GPS_DISABLED: "GPS CONTEXT: DISABLED",

    // Analysis Progress Labels
    ANALYSIS_TITLE: "ANALYSIS IN PROGRESS",
    PROCESS_ACTIVE_LABEL: "PROCESS_ACTIVE",
    DATA_STREAM_LABEL: "SATELLITE_DATA_STREAM",
    RESOLUTION_LABEL: "RESOLUTION",
    TIMESTAMP_LABEL: "TIMESTAMP",
    ETA_LABEL: "ESTIMATED_TIME_REMAINING",
    OVERALL_COMPUTATION_TITLE: "OVERALL_COMPUTATION",
    COMPUTATION_SUBTITLE: "Processing spectral layers (12.4GB)",
    LOADING_TEXT: "LOADING...",
    SYSTEM_NOTE_TITLE: "NOTE: MULTI_SPECTRAL_EXPORT_AVAILABLE",
    SYSTEM_NOTE_CONTENT: "Once analysis is 100% complete, user can export datasets to hardware controllers.",

    // Step Labels
    STEP_CROP_IDENTIFICATION_TITLE: "IDENTIFYING CROP TYPE",
    STEP_HEALTH_ASSESSMENT_TITLE: "ASSESSING HEALTH",
    STEP_YIELD_PREDICTION_TITLE: "PREDICTING YIELD",

    STEP_CROP_IDENTIFICATION_ACTIVE: "Analyzing spectral signatures...",
    STEP_HEALTH_ASSESSMENT_PENDING: "Waiting for previous step...",
    STEP_HEALTH_ASSESSMENT_ACTIVE: "Calculating NDVI indices & Chlorophyll...",
    STEP_YIELD_PREDICTION_PENDING: "Waiting for previous step...",
    STEP_YIELD_PREDICTION_ACTIVE: "Model processing historical data...",
};
