export const METRIC_LABELS = {
    DETECTED_CROP: "DETECTED CROP",
    CURRENT_HEALTH: "CURRENT_HEALTH",
    YIELD_GAP: "YIELD GAP",
    YIELD_QUANTITY: "YIELD QUANTITY",
    TARGET: "TARGET",
    PREDICTED: "PREDICTED",
    YIELD_EXT: "Yield Est",
    GAP_LABEL: "GAP",
    PREDICTED_VS_TARGET: "PREDICTED VS TARGET YIELD",
    METRIC_SEASON: "METRIC: TONS / SEASON"
};

export const CHART_LABELS = {
    TITLE: "YIELD POTENTIAL WINDOW",
    SUBTITLE: "WEEKLY HARVEST ANALYSIS • PREDICTED TONS PER UNIT",
    TARGET_THRESHOLD: "TARGET YIELD THRESHOLD",
    WEEK: "Week",
    YIELD: "Yield",
    OPTIMAL: "OPTIMAL PERIOD",
    EARLY: "EARLY HARVEST",
    LATE: "LATE HARVEST",
    TARGET_LINE: "TARGET YIELD"
};

export const SPATIAL_LABELS = {
    TITLE: "SPATIAL DATA",
    SUBTITLE: "FIELD SECTOR A-12 OVERLAY",
    FOCUS_ZONE: "FOCUS_ZONE",
    VARIATION_KEY: "VARIATION KEY",
    HIGH: "HIGH",
    MED: "MED",
    LOW: "LOW"
};

export const RECOMMENDATION_LABELS = {
    TITLE: "SYSTEM RECOMMENDATIONS"
};

export const LABELS = {
    PAGE_TITLE: "CROP ANALYSIS",
    UPLOAD_IMAGE: "UPLOAD IMAGE",
    INPUT_DATA: "INPUT DATA",
    START_ANALYSIS: "START ANALYSIS",
    CANCEL: "CANCEL",
    PROCESS_ACTIVE_LABEL: "PROCESS ACTIVE",
    ANALYSIS_TITLE: "ANALYSIS IN PROGRESS",
    DATA_STREAM_LABEL: "DATA STREAM",
    RESOLUTION_LABEL: "RESOLUTION",
    TIMESTAMP_LABEL: "TIMESTAMP",
    SYSTEM_NOTE_TITLE: "SYSTEM NOTE",
    SYSTEM_NOTE_CONTENT: "SYSTEM IS OPERATING IN LOW-FIDELITY WIREFRAME MODE. ALL DATA SHOWN IS SIMULATED FOR PROTOTYPING PURPOSES.",
    STEP_CROP_IDENTIFICATION_TITLE: "CROP IDENTIFICATION",
    STEP_CROP_IDENTIFICATION_ACTIVE: "Processing spectral signature...",
    STEP_HEALTH_ASSESSMENT_TITLE: "HEALTH ASSESSMENT",
    STEP_HEALTH_ASSESSMENT_ACTIVE: "Calculating NDVI indices...",
    STEP_HEALTH_ASSESSMENT_PENDING: "Pending spectral data...",
    STEP_YIELD_PREDICTION_TITLE: "YIELD PREDICTION",
    STEP_YIELD_PREDICTION_ACTIVE: "Running ML prediction model...",
    STEP_YIELD_PREDICTION_PENDING: "Waiting for health assessment..."
};
