export const PAGE_TITLES = {
    YIELD_RESULTS: "YIELD PLANNING RESULTS"
};

export const BUTTON_LABELS = {
    SHARE: "SHARE",
    EXPORT_PDF: "EXPORT PDF",
    WEEKLY: "WEEKLY",
    DAILY: "DAILY"
};

export const NAV_LABELS = {
    DASHBOARD: "DASHBOARD",
    ANALYSIS: "CROP ANALYSIS",
    STRESS: "STRESS",
    ORDERS: "ORDERS",
    OVERVIEW: "OVERVIEW",
    YIELD_RESULTS: "YIELD RESULTS",
    FIELD_MAP: "FIELD_MAP",
    REPORTS: "REPORTS"
};
